### ISSUE TITLE
'DigiKeyboard' does not name a type

### ISSUE THREAD

**Issue by ghost** [CedArctic/digiQuack#7]
I converted the script, and even tried adding #include "DigiKeyboard.h" at the top of the script, but no matter what, I get the error 'DigiKeyboard' does not name a type when compiling before uploading to the digispark.

**Comment by CedArctic** [comment]
@SamGurdus1 Have you successfully compiled and uploaded other digispark scripts on the same computer? Say for example one of those in my other repository. Because this looks like an issue regarding your local arduino IDE's configuration of the board and its libraries. See for more info: https://digistump.com/wiki/digispark/tutorials/connecting
